### ISSUE TITLE
Where are the Alert definition for the Alerts from the runbook

### ISSUE THREAD

**Issue by ulikl** [kubevirt/monitoring#163]
Hi,

 in the current kubevirt operator only a subset of the Alerts documented in this repo are defined.

 source: https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-operator/resource/generate/components/prometheus.go
 
 Where can I find the definition for the other alerts?

**Comment by sradco** [comment]
All alerts include a runbook. Perhaps you are referring to recording rules?

**Comment by sradco** [comment]
@ulikl Sorry for the delay. These alerts were removed since they were determined as too opinionated and may not fit all clusters. But it is possible to add them as custom alerts if you require them.
The runbooks were left by accident and I removed them now.
