### ISSUE TITLE
Add Phase Transition dashboard

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/monitoring#37]
After https://github.com/kubevirt/kubevirt/pull/5766 merged, it gave us the ability to view how quickly VMIs progress through their phases.  It would be good to have a shared dashboard to view this data.

![121600439-7371ec00-ca12-11eb-92c3-09b912a0f202](https://user-images.githubusercontent.com/6795213/131842230-3548f852-8927-4dff-9fe4-156ada446484.jpg)

**Comment by rthallisey** [comment]
@marceloamaral

**Comment by marceloamaral** [comment]
This is related to https://github.com/kubevirt/monitoring/pull/38

**Comment by sradco** [comment]
@marceloamaral @rthallisey #38 is merged. Can we close this issue?
