### ISSUE TITLE
Please make this repo usable for the kubevirt community

### ISSUE THREAD

**Issue by rmohr** [kubevirt/monitoring#39]
Taking the comment from https://github.com/kubevirt/monitoring/pull/38#issuecomment-913425471:

> Note that this repo is source of truth for dashboards. The files here are JSON files and compatible with OCP UI and Grafana. They will be consumed by hyperconverged-cluster-operator for OCP UI.
> 
> The job below fetches all json files here and convert them to yaml for k8s configmaps.
> https://github.com/kubevirt/hyperconverged-cluster-operator/actions/workflows/dashboard-updater.yml
> 
> Existing dashboards are here:
> https://github.com/kubevirt/hyperconverged-cluster-operator/tree/main/assets/dashboards
> 
> Then HCO will deploy them during installation automatically and OCP UI will display them.
> 
> Therefore, we need to ensure that this dashboard works in OCP UI as well.

This make the repo unusable for  the community and PRs like https://github.com/kubevirt/monitoring/pull/38 can realistically never be added to this repo.

Please either add proper e2e testing and releases or move openshift-only dashboards directly to HCO.

**Comment by sradco** [comment]
To fix this issue we created new sub folders under "dashboards":
 -  "grafana" for community dashboards 
 -  "openshift" for dashboards that are both community and openshift compatible.

**Comment by sradco** [comment]
https://github.com/kubevirt/monitoring/pull/40
