### ISSUE TITLE
Remove potentially unsupported action in LowKVMNodesCount runbooks

### ISSUE THREAD

**Issue by djfjeff** [kubevirt/monitoring#49]
The runbooks docs/runbooks/LowKVMNodesCount.md points to enabling software emulation fallback, which is an unsupported action in downstream. This section should be removed or at least put in a warning for downstream user.

**Comment by sradco** [comment]
Hi @andreyod, Can you  please take this?

**Comment by andreyod** [comment]
Opened #50

**Comment by sradco** [comment]
PR #50 fixes this issue.
